# Generated by Django 4.2.2 on 2023-07-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='description',
        ),
        migrations.AlterField(
            model_name='version',
            name='is_current',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Актуальность'),
        ),
    ]
